package main

import (
	"fmt"
	"mapreduce"
	"os"
	"unicode"
	"strings"
	"sort"
	"strconv"
)

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func mapF(filename string, contents string) []mapreduce.KeyValue {
	// Your code here (Part II).
	f := func(c rune) bool {
		return !unicode.IsLetter(c)
	}
	raws := strings.FieldsFunc(contents, f)

	var words []string
	for _,raw := range raws {
		word := strings.Fields(raw)
		words = append(words, word...)
	}

	var keys []string
	var mid = make(map[string]int64)
	for _,w := range words {
		if _,ok := mid[w];!ok {
			mid[w] = 1
			keys = append(keys, w)
		} else {
			mid[w] = mid[w] + 1
		}
	}
	sort.Strings(keys)

	var res []mapreduce.KeyValue
	for _,key := range keys {
		res = append(res, mapreduce.KeyValue{key, strconv.FormatInt(mid[key], 10)})
	}

	return res
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func reduceF(key string, values []string) string {
	// Your code here (Part II).
	var sum int64
	sum = 0
	for _,sub := range values {
		i, err := strconv.ParseInt(sub, 10, 64)
		if err == nil {
			sum = sum + i
		}
	}
	return strconv.FormatInt(sum, 10)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
